### ISSUE TITLE
Can I configure the number of parallel jobs?

### ISSUE THREAD

**Issue by gussmith23** [octoml/tvm-build#10]
I'm building in a Docker image on my laptop, which has a problem with parallel jobs when building TVM. Can I tune down the number of parallel jobs?

**Comment by gussmith23** [comment]
Hm, actually, the logs indicate it might actually be building with -j1.

**Comment by areusch** [comment]
@gussmith23 in general we prefer to keep the GitHub issues to actionable requests. could you ask your question on our discuss forum http://discuss.tvm.ai (and could you include a little more detail e.g. what command you ran)?
